download:
  seed: 20240402
  year: 2023
  n_locs: 20
  base_url: https://www.ncei.noaa.gov/data/local-climatological-data/access/
  destination: data/archive/
  link_parser: data/content.html
  hourly_features:
  - HourlyRelativeHumidity
  - HourlyDryBulbTemperature
  - HourlyDewPointTemperature
  - HourlySeaLevelPressure
  - HourlyStationPressure
  monthly_features:
  - MonthlyAverageRH
  - MonthlyMeanTemperature
  - MonthlyDewpointTemperature
  - MonthlySeaLevelPressure
  - MonthlyStationPressure
n_locs: 15
